name: boostsecurity.io
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  boost-sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.1
      - name: test
        run: |
          echo ">ACTIONS"
          echo ">ACTIONS"
          echo ">ACTIONS"
          ls -Al /home/runner/work/_actions
          echo ">ACTIONS>*"
          echo ">ACTIONS>*"
          echo ">ACTIONS>*"
          ls -Al /home/runner/work/_actions/*
          echo ">ACTIONS>action org>action name>action version>"
          echo ">ACTIONS>action org>action name>action version>"
          echo ">ACTIONS>action org>action name>action version>"
          ls -Al /home/runner/work/_actions/*/*/*
