name: boostsecurity.io
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  boost-sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.1
      - name: test
        run: |
          ls -Al $GITHUB_ACTION_PATH || true
          env
          ls -Al /home/runner/work/_actions/
